Adiciona: "Cifra de Ngolônia" OBI 2021
ifpe-open-source/competicoes-de-programacao pull request #15
Opened 2022-05-25 02:24 UTC by Gvinfinity

Adiciona o problema Cifra de Ngolônia da OBI 2021, em Python.

2022-05-25 12:40 UTC, weltonfelix requested changes
Solução muito boa, Gabriel!! Somente algumas mudanças para facilitar a leitura do README.

2022-05-25 12:40 UTC, weltonfelix commented on obi/2021/cifra-da-nlogonia/README.md
> +    <li>a vogal mais próxima da consoante original no alfabeto, com a regra adicional de que se a consoante original está à mesma </li>distância de duas vogais, então a vogal mais próxima do início d
```suggestion
    <li>a vogal mais próxima da consoante original no alfabeto, com a regra adicional de que se a consoante original está à mesma distância de duas vogais, então a vogal mais próxima do início do alfabeto é usada. Por exemplo, se a consoante original é `d`, a vogal que deve ser usada é `e`, pois esta é a vogal mais próxima; se a consoante original é `c`, a vogal que deve ser utilizada é `a`, porque `c` está à mesma distância de `a` e `e`, e `a` é mais próxima do início do alfabeto.</li>
```

2022-05-25 12:40 UTC, weltonfelix commented on obi/2021/cifra-da-nlogonia/README.md
> +    <li>a própria consoante (vamos chamar de consoante original);</li>
```suggestion
    <li>a própria consoante (vamos chamar de `consoante original`);</li>
```

2022-05-25 12:40 UTC, weltonfelix commented on obi/2021/cifra-da-nlogonia/README.md
> +    <li>a consoante que segue a consoante original, na ordem do início ao fim do alfabeto. Por exemplo, se a consoante original é d, a </li>consoante a ser utilizada é f. No caso de a consoante origi
```suggestion
    <li>a consoante que segue a consoante original, na ordem do início ao fim do alfabeto. Por exemplo, se a consoante original é `d`, a consoante a ser utilizada é `f`. No caso de a consoante original ser `z`, deve ser utilizada a própria letra `z`.</li>
```

2022-05-25 19:05 UTC, weltonfelix requested changes
Acabou que quando misturou o markdown com o HTML, o GitHub não interpretou os ( ` ) dentro dos itens da lista HTML como formatação em markdown pra código.

Acho que poderia deixar a lista inteira em markdown, já que também facilita a leitura caso alguém baixe o código e não esteja vendo o markdown renderizado.

2022-05-27 02:07 UTC, weltonfelix approved these changes

2022-05-27 19:39 UTC, fabiopapais approved these changes

2022-05-27 19:39 UTC, merged